try {
    anotherFunction();
} catch {
    console.log('Esto es un error');
}